app/urls.py
from django.urls import path
from . import views

app_name = "app"

urlpatterns = [
    path("home/",views.index,name="index"),
    path("aboutus/", views.aboutus, name="aboutus"),
    path("account/", views.account, name="account"),
    path("activities/", views.activities, name="activities"),
    path("events/chosen-event/", views.chosenEvent, name="events_chosen-event"),
    path("events/chosen-place/", views.chosen_place, name="events_chosen-place"),
    path("events/", views.events, name="events"),
    path('events/<int:event_id>/', views.event_detail, name='event_detail'),
    path("account/signup/learn-more", views.learnMore, name="account_signup_learn-more"),
    path("account/my-plans/", views.myPlans, name="account_my-plans"),
    path("account/my_account/", views.my_account, name="my_account"),
    path('account/delete/', views.delete_account, name='delete_account'),
    path('account/upload_profile_picture/', views.upload_profile_picture, name='profile_picture_upload'),
    path('account/profile_picture_delete/', views.delete_profile_picture, name='profile_picture_delete'),
    path("places/", views.places, name="places"),
    path("places/<slug:place_name_slug>/", views.chosen_place, name="chosen-place"), #mapping a place url to the chosen_place view
    path('places/<slug:place_name_slug>/reviews/', views.place_reviews, name='place_reviews'), #reviews for each chosen place
    path('places/<slug:place_name_slug>/submit-review/', views.submit_place_review, name='submit_place_review'), #used for the view to submit review for place
    path("places/<str:category>/", views.places, name="places"),
    path("account/signup/private-policy", views.privatePolicy, name="account_signup_private-policy"),
    path("account/signup/", views.register, name="account_signup"),
    path("account/signup/terms-of-use", views.register, name="account_signup_terms-of-use"),
    path("plans/", views.plans, name="plans"),
    path("plans/<int:plan_id>/reviews/", views.plan_reviews, name="plan_reviews"),
    path("plans/<int:plan_id>/submit-review/", views.submit_plan_review, name='submit_plan_review'),
    path("account/my-plans/chosen-plan/", views.specificPlan, name="account_my-plans_chosen-plan"),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('restricted/', views.restricted, name='restricted'),
    path('logout/', views.user_logout, name='logout'),
    path('delete-account/', views.delete_account, name='delete_account'),
    path("about-us/", views.about_us, name="about-us"),
    path("activities/", views.activities, name="activities"),
    path("events/", views.events, name="events"),
    path("language/", views.language, name="language"),
    path("map/", views.map, name="map"),
    path("search-events/",views.search_events,name="search-events"),
    path('search-activities/', views.search_activities, name='search-activities'),
    path("process-plans/",views.process_plan,name="process-plans"),
    path("browsePlans/",views.browsePlans,name="browsePlans"),
    path('plans/<int:plan_id>/', views.specificPlan, name='specific_plan'),
    path("activities/",views.get_category_activities,name='get_category_activities'),
    path('activities/', views.get_activities_by_category, name='get_activities_by_category'),
    path('activities/', views.add_activity, name='add_activity')
]

explore_glasgow/urls.py
# ollies branch
from django.contrib import admin
from django.urls import include, path
from app import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", views.index, name="index"),
    path("app/", include("app.urls")),
    path("admin/", admin.site.urls),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('account/my_account/', views.my_account, name='my_account'),
    path('account/upload_profile_picture/', views.upload_profile_picture, name='profile_picture_upload'),
    path("about-us/", views.about_us, name="about-us"),
    path("activities/", views.activities, name="activities"),
    path("events/", views.events, name="events"),
    path("map/", views.map, name="map"),
    path("places/", views.places, name="places"),
    path("browsePlans/",views.browsePlans,name="browsePlans"),
    path('events/', views.events, name='events'),
    path('events/<int:event_id>/', views.event_detail, name='event_detail'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#path("", include('app.urls', namespace='app')),

templates/app/aboutus.html
{% extends 'app/base.html' %}
{% load static %}

{% block title_block %}
    About Us
{% endblock %}

{% block additional_styles %}
    <link rel="stylesheet" href="{% static 'styling/about-us.css' %}">
{% endblock %}

{% block body_block %}
<h1>About Us</h1>
<div class="profile-cards-container">
    {% for member in team_members %}
    <div class="profile-card">
        <img src="{% static member.image %}" alt="Profile photo of {{ member.name }}">
        <h2>{{ member.name }}</h2>
        <p><a href="{{ member.account_link }}">View Profile</a></p>
        <p>{{ member.bio }}</p>
        <div class="social-links">
            <a href="{{ member.instagram_link }}"><i class="fab fa-instagram"></i></a>
            <a href="mailto:{{ member.email }}"><i class="fas fa-envelope"></i></a>
            <a href="{{ member.linkedin_link }}"><i class="fab fa-linkedin"></i></a>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

templates/app/activities.html
{% extends 'app/base.html' %}
{% load app_template_tags %}

{% load static %}

{% block title_block %}
    Activities
{% endblock %}
    
{% block additional_styles %}<link rel="stylesheet" href="{% static 'styling/activities.css' %}">{% endblock %}
    {% block additional_js %}
    <script src="{% static 'javascript/activities.js' %}"></script>
    {% endblock %}
    
    {% block body_block %}


<body>

<div class="container">
    <div class="left-section">
        <div id="left-header">
            <h1>Your Activities</h1>
        </div>
        <div class="inner-left-section">
            <div id="activities-list"> 
                  <li><button onclick="get_category_activities('Personal')"> Personal </button></li>
                  <li><button onclick="get_category_activities('Work')"> Work </button></li>
                  <li><button onclick="get_category_activities('fitness')"> Fitness </button></li>
                  <li><button onclick="get_category_activities('Education')"> Education </button></li>
                  <li><button onclick="get_category_activities('Social')"> Social </button></li>
                  <li><button onclick="get_category_activities('Hobbies')"> Hobbies </button></li>
                </ul>
            </div>
            <div class="main-section-left">
                <div id="user-activities">
                    <ul>
                      {% for activity in activities %}
                        <li>{{ activity.title }} - {{ activity.description }}</li>
                      {% empty %}
                        <li>No activities found.</li>
                      {% endfor %}
                    </ul>
                  </div>
            </div>
        </div>
    </div>
    <div class="right-section">
        <div id="right-header">
            <h1>New Activity</h1>
        </div>
        <div class="main-section-right" id="main-section-right">
        </div>
        <label for="durationSlider">Event Duration (hours): </label>
        <input type="range" id="durationSlider" name="duration" min="1" max="24" value="1">
        <span id="durationDisplay">1</span> hours

    
        <div class="input-group">
            <input type="text" class="search-database" id="activity-name" name="activity-name" placeholder="Search activities..." oninput="activity_autocomplete()">
            <button onclick="addExistingActivity()"><i class="fas fa-plus"></i></button>
            <div id="autocomplete-results-activities" class="autocomplete-results"></div>
        </div>
        
        <button onclick="showActivityForm()">Add New Activity</button>


<div id="activity-details-popup" style="display:none;">
    <form id="new-activity-form">
        {% csrf_token %}
      <label for="activity-name">Activity Name:</label>
      <input type="text" id="activity-name" name="activity-name"><br>
      <label for="description">description</label>
      <input type="text" id="description" name="description"><br>
      <label for="location">Location:</label>
      <input type="text" id="location" name="location"><br>
      <label for="duration">Duration (hours):</label>
      <input type="number" id="duration" name="duration"><br>
      <button type="button" onclick="addNewActivity()"> Submit</button>
    </form>
  </div>


<div id="activity-details-popup" style="display:none;">
    <form id="new-activity-form">
        {% csrf_token %}
      <label for="activity-name">Activity Name:</label>
      <input type="text" id="activity-name" name="activity-name"><br>
      <label for="description">description</label>
      <input type="text" id="description" name="description"><br>
      <label for="location">Location:</label>
      <input type="text" id="location" name="location"><br>
      <label for="duration">Duration (hours):</label>
      <input type="number" id="duration" name="duration"><br>
      <button type="button" onclick="addNewActivity()"> Submit</button>
    </form>
  </div>
  

        
    </div>
</div>
</body>
    {% endblock %}
</html>

templates/app/browsePlans.html
{% extends 'app/base.html' %}
{% load static %}

{% block title_block %}Browse Plans{% endblock %}

{% block additional_styles %}
<link rel="stylesheet" href="{% static 'styling/browsePlans.css' %}">
{% endblock %}

{% block body_block %}
<h1>Browse All Plans</h1>
<div class="plans-container">
    {% for plan in plans %}
    <div class="plan-card">
        <div class="plan-info">
            <h3>{{ plan.title }}</h3>
            <!-- Updated part: Add .username-link class to the username link -->
            <p><a href="#" class="username-link">@{{ plan.user.username }}</a></p>
            <a href="{% url 'app:specific_plan' plan.id %}" class="view-plan-btn">View Full Plan</a>
        </div>
        <div class="plan-schedule">
            <h4>Schedule</h4>
            <ul>
                {% for item in plan.schedule_details %}
                <li>{{ item.title }} at {{ item.time|date:"H:i" }}</li>
                {% endfor %}
            </ul>
        </div>
    </div>
    {% empty %}
    <p>No plans available.</p>
    {% endfor %}
</div>
{% endblock %}

templates/app/chosen_place.html
{% extends 'app/base.html' %}
{% load static %}

{% block title_block %}
    {{ place.name }}
{% endblock %}

{% block body_block %}
  <body style="padding-left: 10px;">
    {% if place %}
        <h1 style="display: inline;">{{ place.name }}</h1>

        <!--Link to return to places.html-->
        <a href="{% url 'app:places' %}" style="display:inline; margin-left: 20px;">--Back to all places--</a>
        <hr>
        <!--Image of place-->
        <div style="text-align: left;">
          <img src="{% static image %}" alt="Picture of {{ place.name }}" style="display: block; width: 50%;"> <!--Add path to image as src-->
        </div><br>

        <a href="https://www.google.com/maps/search/?api=1&query=Google&query_place_id={{place.location}}"
         style="color: #004b7a; text-decoration: underline;">
            See location in Google Maps (leave site)</a>
        <br><br>

        <h2>Upcoming events at {{ place.name }}</h2>
        <!--Listing upcoming events if any as a description list-->
          {% if events %}
          <dl>
            {% for event in events %}
            <!--List all upcoming events at the place-->
              <dt style="color: #7a0000">{{ event.title }}</dt>
              <!--Could add a href link to the event here-->
              <dd><strong>{{ event.start_time }}</strong> to <strong>{{ event.end_time }}</strong></dd> <!--Need to make sure this works-->
            {% endfor %}
          </dl><br>
          {% else %}
            <p>There are currently no upcoming events here.</p>
          {% endif %}
          <br>
        <div style="display: flex; justify-content: space-between;">
          <div style="width: 50%; margin-left: 30px;">
            <div style="margin-top: 20px; padding: 20px; background-color: #f9f9f9; border-radius: 10px;">
              <h2>Reviews for {{ place.name }}</h2>
              {% if five_reviews %}
              <ul>
                  {% for review in five_reviews %}
                  <li>
                      <strong>{{ review.user.username }}: </strong>{{ review.rating }} ★ - {{ review.content }}
                  </li>
                  {% endfor %}
              </ul>
              <p>Average rating of {{ avg_rating|floatformat:"1" }} ★ from {{ num_reviews }} reviews, <a href="{% url 'app:place_reviews' place.slug %}" style="color: blue; text-decoration: underline;">read all reviews</a></p>
              {% else %}
              <p>No reviews yet.</p>
              {% endif %}
            </div>
          </div>
          <div style="width: 45%;">
            <div style="margin-top: 20px; padding: 20px; background-color: #f9f9f9; border-radius: 10px; margin-right: 30px;">
              <h3>Leave a review for {{ place.name }}</h3>
              <form method="POST" action="{% url 'app:submit_place_review' place.slug %}">
                  {% csrf_token %}
                  <label for="content"><strong>Review:</strong></label>
                  <textarea name="content" placeholder="Write your review here" style="width: 100%; height: 100px;" required></textarea>
                  <br>
                  <label for="rating"><strong>Rating ★ (1-5):</strong></label>
                  <input type="number" id="rating" name="rating" min="1" max="5" style="margin-left: 5px;" required>
                  <br>
                  <button type="submit">Submit Review</button>
              </form>
            </div>
          </div>
        </div>
    {% else %}
        The specified place does not exist.
    {% endif %}
  </body>
{% endblock %}

templates/app/delete_account.html
{% extends 'app/base.html' %}
{% load static %}

{% block title_block %}
    Delete Account
{% endblock %}

{% block body_block %}
<h1>Delete Your Account</h1>
<p>Are you sure you want to delete your account? This action is irreversible.</p>
<form id="delete_account_form" method="post" action="{% url 'app:delete_account' %}" onsubmit="return confirmDelete();">
    {% csrf_token %}
    <input type="submit" value="Yes, delete my account"/>
    <a href="{% url 'app:index' %}">No, take me back</a>
</form>
<script>
    function confirmDelete() {
        return confirm('Are you sure? This action cannot be undone.');
    }
</script>
{% endblock %}

{% block user_block %}
{% endblock %}

templates/app/event_detail.html
{% extends 'app/base.html' %}
{% load static %}

{% block title_block %}
    {{ event.title }}
{% endblock %}

{% block body_block %}
    {% if event %}
        <h1 style="display: inline;">{{ event.title }}</h1>
        
        <!--Link to return to event.html-->
        <a href="{% url 'app:events' %}" style="display:inline; margin-left: 20px;">--Back to all events--</a>
        <hr>

        <!--Image of event-->
        <div style="text-align: left;">
            <img src="{% static image %}" alt="Picture of {{ event.title }}" style="display: block; width: 80%;"> <!--Add path to image as src-->
        </div><br>

        <h2>Event Details</h2>
        <p><strong>Description:</strong> {{ event.description }}</p>
        <p><strong>Start Time:</strong> {{ event.start_time|date:"D, d M Y H:i" }}</p>
        <p><strong>End Time:</strong> {{ event.end_time|date:"D, d M Y H:i" }}</p>
        <p><strong>Location:</strong> {{ event.location }}</p>

    {% else %}
        <p>The specified event does not exist.</p>
    {% endif %}
{% endblock %}

templates/app/events.html
{% extends 'app/base.html' %}
{% load static %}

{% block title_block %}
    Events
{% endblock %}

{% block additional_styles %}
<link rel="stylesheet" href="{% static 'styling/listings.css' %}">
{% endblock %}

{% block body_block %}
<h1>What's on?</h1>

<div class="grid-container">
  {% block topbar %}
    <div class="header">
      <ul class="inline">
        {% for month in month_names %}
        <li><a href="{% url 'app:events' %}?month={{ month }}">{{ month }}</a></li>
        {% endfor %}
        <li><a href="{% url 'app:events' %}">All</a></li>
      </ul>
    </div>
  {% endblock %}

  <div class="left" style="background-color:#bbb; padding: 20px;">
    <form action="#" method="get">
      <input type="search" name="q" placeholder="Search events..." aria-label="Search events" style="width: 100%; padding: 5px; margin-bottom: 10px;">
      <!--Checkbox-->
      <h3>Filter:</h3>
      <label for="specific-date" style="display: block;">Specific Date:</label>
      <input type="date" id="specific-date" name="date" style="width: 100%; padding: 5px; margin-bottom: 10px;">

      {% for tag in tags %}
        <div style="margin-bottom: 10px;">
          <input type="checkbox" id="tag_{{ tag.id }}" name="tags" value="{{ tag.id }}">
          <label for="tag_{{ tag.id }}">{{ tag.name }}</label>
        </div>
      {% endfor %}

      <input type="submit" value="Apply Filters" style="width: 100%; padding: 5px; margin-top: 10px;">
    </form>
  </div>  
  
  <div class="right" style="padding: 20px;">
    <div class="event-cards" style="display: flex; flex-wrap: wrap; gap: 10px; justify-content: flex-start;">
      {% for event in events %}
      <!-- Each event card has a width set to calc(33.333% - 10px) to keep three in a row -->
      <div class="event-card" style="border: 1px solid #ccc; padding: 10px; flex: 0 0 calc(33.333% - 10px); box-sizing: border-box; margin-bottom: 10px;">
        <a href="{% url 'event_detail' event.id %}" style="text-decoration: none; color: inherit;">
          <div style="height: 200px; background-color: #f3f3f3; margin-bottom: 10px;">
            {% if event.image %}
              <img src="{% static event.image %}" alt="{{ event.title }}" style="max-height: 200px; width: 100%; object-fit: cover;">
            {% else %}
              <img src="{% static 'path/to/placeholder-image.jpg' %}" alt="No image available" style="max-height: 200px; width: 100%; object-fit: cover;">
            {% endif %}
          </div>
          <h3 style="margin: 0;">{{ event.title }}</h3>
          <p style="margin: 0;">{{ event.location }}</p>
          <p style="margin: 0;">{{ event.date|date:"D, d M Y" }}</p>
        </a>
      </div>
        <!-- Clearfix after every third event card -->
        {% if forloop.counter|divisibleby:3 %}
          <div style="width: 100%;"></div>
        {% endif %}
      {% empty %}
        <div style="width: 100%; text-align: center; padding: 20px;">No events found.</div>
      {% endfor %}
      <div style="clear: both;"></div>
    </div>
  </div>

{% endblock %}

templates/app/login.html
{% extends 'app/base.html' %}
{% load static %}

{% block title_block %}
    Login
{% endblock %}

{% block additional_styles %}
    <link rel="stylesheet" href="{% static 'styling/login.css' %}">
{% endblock %}

{% block body_block %}
<div class="form-container">
    <h1>Login to Explore Glasgow</h1>
    <form id="login_form" method="post" action="{% url 'app:login' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="submit-container">
            <input type="submit" value="Submit" />
        </div>
    </form>
    <p>Don't have an account? <a href="{% url 'app:register' %}">Register <span style="color:#8d5d5d">here</span></a>.</p>
</div>
{% endblock %}

templates/app/place_reviews.html
{% extends 'app/base.html' %}
{% load static %}

{% block title_block %}
    Reviews for {{ place.name }}
{% endblock %}

{% block body_block %}
    <h1 style="display: inline;">Reviews for {{ place.name }}</h1>

    <!--Link to return to chosen place.html-->
    <a href="{% url 'app:chosen-place' place.slug %}" style="display:inline; margin-left: 20px;">--Back to {{ place.name }}--</a>
    <hr>

    <div style="display: inline-block; margin-left: 30px;">
        <h3 style="display: inline;">Average Rating ★: {{ avg_rating|floatformat:"1" }}</h3>
        <h3 style="display: inline; margin-left: 20px;">Total Reviews: {{ num_reviews }}</h3>
    </div>

    <div style="display: flex; justify-content: space-between; margin-top: 20px;">
        <div style="width: 45%; margin-left: 70px;">
            {% if reviews %}
            <ul>
                {% for review in reviews %}
                <li>
                    <strong>{{ review.user.username }}: </strong>{{ review.rating }} ★ - {{ review.content }}
                </li>
                {% endfor %}
            </ul>
            {% else %}
            <p>No reviews yet.</p>
            {% endif %}
        </div>
        <div style="width: 45%;">
            <div style="margin-top: 20px; padding: 20px; background-color: #f9f9f9; border-radius: 10px; margin-right: 50px;">
            <h3>Leave a review for {{ place.name }}</h3>
            <form method="POST" action="{% url 'app:submit_place_review' place.slug %}">
                {% csrf_token %}
                <label for="content"><strong>Review:</strong></label>
                <textarea name="content" placeholder="Write your review here" style="width: 100%; height: 100px;" required></textarea>
                <br>
                <label for="rating"><strong>Rating ★ (1-5):</strong></label>
                <input type="number" id="rating" name="rating" min="1" max="5" style="margin-left: 5px;" required>
                <br>
                <button type="submit">Submit Review</button>
            </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/app/plan_reviews.html
{% extends 'app/base.html' %}
{% load static %}

{% block title_block %}
    Reviews for {{ plan.title }}
{% endblock %}

{% block body_block %}
    <h1 style="display: inline;">Reviews for {{ plan.title }}</h1>

    <!--Link to return to chosen plan.html-->
    <a href="{% url 'app:specific_plan' plan.id %}" style="display:inline; margin-left: 20px;">--Back to {{ plan.title }}--</a>
    <hr>

    <div style="display: inline-block; margin-left: 30px;">
        <h3 style="display: inline;">Average Rating ★: {{ avg_rating|floatformat:"1" }}</h3>
        <h3 style="display: inline; margin-left: 20px;">Total Reviews: {{ num_reviews }}</h3>
    </div>

    <div style="display: flex; justify-content: space-between; margin-top: 20px;">
        <div style="width: 45%; margin-left: 70px;">
            {% if reviews %}
            <ul>
                {% for review in reviews %}
                <li>
                    <strong>{{ review.user.username }}: </strong>{{ review.rating }} ★ - {{ review.content }}
                </li>
                {% endfor %}
            </ul>
            {% else %}
            <p>No reviews yet.</p>
            {% endif %}
        </div>
        <div style="width: 45%;">
            <div style="margin-top: 20px; padding: 20px; background-color: #f9f9f9; border-radius: 10px; margin-right: 50px;">
            <h3>Leave a review for {{ plan.title }}</h3>
            <form method="POST" action="{% url 'app:submit_plan_review' plan.id %}">
                {% csrf_token %}
                <label for="content"><strong>Review:</strong></label>
                <textarea name="content" placeholder="Write your review here" style="width: 100%; height: 100px;" required></textarea>
                <br>
                <label for="rating"><strong>Rating ★ (1-5):</strong></label>
                <input type="number" id="rating" name="rating" min="1" max="5" style="margin-left: 5px;" required>
                <br>
                <button type="submit">Submit Review</button>
            </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/app/register.html
{% extends 'app/base.html' %}
{% load static %}

{% block title_block %}
    Register
{% endblock %}

{% block additional_styles %}
    <link rel="stylesheet" href="{% static 'styling/login.css' %}">
{% endblock %}

{% block body_block %}
<div class="form-container">
    <h1>Sign Up to Explore Glasgow</h1>
    {% if registered %}
        <strong>Thank you for registering!</strong>
        <a href="{% url 'app:index' %}">Return to the homepage.</a>
    {% else %}
        <form id="user_form" method="post" action="{% url 'app:register' %}" enctype="multipart/form-data">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}
            <div class="submit-container">
                <input type="submit" name="submit" value="Register" />
            </div>
        </form>
        <p>Already have an account? <a href="{% url 'app:login' %}">Login <span style="color:#8d5d5d">here</span></a>.</p>
    {% endif %}
</div>
{% endblock %}

templates/app/restricted.html
{% extends 'app/base.html' %}
{% load static %}

{% block title_block %}
    Restricted Page
{% endblock %}

{% block body_block %}
<h2>Restricted Page</h2>
    <p>This page is for registered users only.</p>
{% endblock %}

templates/app/specificPlan.html
{% extends 'app/base.html' %}
{% load static %}

{% block title_block %}{{ plan.title }}{% endblock %}

{% block additional_styles %}
<link rel="stylesheet" href="{% static 'styling/specificPlan.css' %}">
{% endblock %}

{% block body_block %}
<div class="plan-page-container">
    <div class="plan-detail-container">
        <h1>{{ plan.title }}</h1>
        <p><a href="#" class="username-link">@{{ plan.user.username }}</a></p>
        <h2>Schedule</h2>
        <ul>
            {% for item in schedule_details %}
            <li>
                <span class="schedule-time">{{ item.time|date:"H:i" }}</span>
                <span class="schedule-title">{{ item.title }}</span>
            </li>
            {% endfor %}
        </ul>
    </div>
    <div style="display: flex; justify-content: space-between;">
        <div style="width: 50%; margin-left: 30px;">
          <div style="margin-top: 20px; padding: 20px; background-color: #f9f9f9; border-radius: 10px;">
            <h2>Reviews for {{ plan.title }}</h2>
            {% if five_reviews %}
            <ul>
                {% for review in five_reviews %}
                <li>
                    <strong>{{ review.user.username }}: </strong>{{ review.rating }} ★ - {{ review.content }}
                </li>
                {% endfor %}
            </ul>
            <p>Average rating of {{ avg_rating|floatformat:"1" }} ★ from {{ num_reviews }} reviews, <a href="{% url 'app:plan_reviews' plan.id %}" style="color: blue; text-decoration: underline;">read all reviews</a></p>
            {% else %}
            <p>No reviews yet.</p>
            {% endif %}
          </div>
        </div>
        <div style="width: 45%;">
          <div style="margin-top: 20px; padding: 20px; background-color: #f9f9f9; border-radius: 10px; margin-right: 30px;">
            <h3>Leave a review for {{ plan.title }}</h3>
            <form method="POST" action="{% url 'app:submit_plan_review' plan.id %}">
                {% csrf_token %}
                <label for="content"><strong>Review:</strong></label>
                <textarea name="content" placeholder="Write your review here" style="width: 100%; height: 100px;" required></textarea>
                <br>
                <label for="rating"><strong>Rating ★ (1-5):</strong></label>
                <input type="number" id="rating" name="rating" min="1" max="5" style="margin-left: 5px;" required>
                <br>
                <button type="submit">Submit Review</button>
            </form>
          </div>
        </div>
    </div>
</div>
{% endblock %}

templates/app/upload_profile_picture.html
{% extends 'app/base.html' %}
{% load static %}

{% block title_block %}
Upload Profile Picture
{% endblock %}

{% block body_block %}
<div class="container" style="max-width: 600px; margin: 20px auto; padding: 20px; background-color: #fff; border-radius: 10px; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);">
    <h1 style="text-align: center; margin-bottom: 20px; color: #333;">Upload Profile Picture</h1>
    <p style="text-align: center; margin-bottom: 20px;">Upload a profile picture by selecting an image file below:</p>

    <form method="post" enctype="multipart/form-data" style="margin-bottom: 20px;">
        {% csrf_token %}
        {{ form.as_p }}

        <!-- File Preview -->
        <div id="file-preview-container" style="display: none; text-align: center; margin-top: 20px;">
            <h3 style="margin-bottom: 10px;">Preview:</h3>
            <img id="file-preview" src="#" alt="Preview" style="max-width: 300px; border-radius: 5px;">
        </div>

        <!-- Submit Button -->
        <button type="submit" class="btn btn-primary" style="display: block; width: 100%; padding: 10px; background-color: #007bff; color: white; border: none; border-radius: 5px; cursor: pointer;">Upload</button>
    </form>

    <!-- Display Uploaded Picture or Message -->
    {% if user_profile.picture %}
    <div class="mt-3" style="text-align: center; margin-top: 20px;">
        <h3>Your Profile Picture:</h3>
        <img src="{{ user_profile.picture.url }}" alt="Profile Picture" style="width: 150px; height: 150px; border-radius: 50%;">
        <form action="{% url 'profile_picture_delete' %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger mt-2" style="margin-top: 10px; padding: 10px; background-color: #dc3545; color: white; border: none; border-radius: 5px; cursor: pointer;">Delete Avatar</button>
        </form>
    </div>
    {% else %}
    <p class="mt-3" style="text-align: center; margin-top: 20px;">No profile picture uploaded yet.</p>
    {% endif %}
</div>

<script type="text/javascript">
    // File input change event listener
    document.getElementById('id_picture').addEventListener('change', function() {
        // Display file preview
        var file = this.files[0];
        if (file) {
            var reader = new FileReader();
            reader.onload = function(e) {
                document.getElementById('file-preview').setAttribute('src', e.target.result);
                document.getElementById('file-preview-container').style.display = 'block';
            }
            reader.readAsDataURL(file);
        }
    });
</script>
{% endblock %}